spring:
  application:
    name: ninja-gateway
  cloud:    gateway:      routes:
      - id: ninjaEnemy
        predicates:
        - Path=/api/**
        uri: ${ninja-app:lb://ninja-app}  
      - id: test
        predicates:
        - Path=/get
        uri: ${tst:http://httpbin.org:80}    
        
server:  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:8761/eureka          