spring:
  application:
    name: ninja-app
  config:
    import:
    - optional:configserver:http://localhost:8765 
  flyway:
    enabled: false
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true      
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ninja
    username: postgres
    password: password
  profiles:
    active: dev
  cloud:
    config:
      profile: dev
server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
      
      
      
      
      
      
      
      
      