spring:
  application:
    name: ninja-weapons-app
  config:
    import:
    - optional:configserver:http://localhost:8765
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ninjaWeapon
    username: postgres
    password: password
  flyway:
    enabled: false
    
server:
  port: 8100
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
      