spring:
  application:
    name: ninja-naming-server
    
server:  port: 8761
  
eureka:  client:    register-with-eureka: false
    fetch-registry: false
  instance:    hostname: locahost    